version: '3.4'

services:
   ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Zelfdwnq9512!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
   operationstacked:
    image: ${DOCKER_REGISTRY-}operationstacked
    build:
      context: .
      dockerfile: OperationStacked/Dockerfile
    ports:
     - "8080:80"
