name: Deploy to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore OperationStacked/OperationStacked.csproj

    - name: Build and test
      run: |
        dotnet build -c Release OperationStackedTests/OperationStackedTests.csproj
        dotnet test OperationStackedTests/OperationStackedTests.csproj

    - name: Publish
      run: dotnet publish -c Release -o published OperationStacked/OperationStacked.csproj

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Create Docker image
      run: |
        docker build -t operation-stacked-api .
        docker tag operation-stacked-api:latest "${{ secrets.ECR_REPOSITORY_URI }}:latest"

    - name: Push Docker image to Amazon ECR
      run: |
        docker push "${{ secrets.ECR_REPOSITORY_URI }}:latest"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
