name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore OperationStacked/OperationStacked.csproj

    - name: Build and test
      run: |
        dotnet build -c Release OperationStackedTests/OperationStackedTests.csproj
        dotnet test OperationStackedTests/OperationStackedTests.csproj

    - name: Publish
      run: dotnet publish -c Release -o published OperationStacked/OperationStacked.csproj

    - name: Create Lambda function zip file
      run: |
        cd OperationStacked/bin/Release/net6.0
        zip -r ../../../../dotnet-api.zip *
        cd ../../../../
        mv dotnet-api.zip ./Terraform/

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Terraform Import - IAM Role
      run: terraform import aws_iam_role.lambda_exec lambda_exec
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true